#!/bin/bash
# Setup and Run Instructions for Inventory Management System

echo "╔════════════════════════════════════════════════════╗"
echo "║   Inventory & Stock Management System              ║"
echo "║   Setup & Run Guide                                ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

echo "📋 Prerequisites:"
echo "  ✓ Node.js (v14+) installed"
echo "  ✓ npm (v6+) installed"
echo ""

echo "🔧 Setup Commands (Run Once):"
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""

echo "🚀 Running the Application:"
echo ""
echo "Terminal 1 - Start Backend (JSON Server):"
echo "   npm run json-server"
echo "   (Runs on http://localhost:3001)"
echo ""

echo "Terminal 2 - Start Frontend (React):"
echo "   npm run dev"
echo "   (Runs on http://localhost:3000)"
echo ""

echo "📚 Build for Production:"
echo "   npm run build"
echo "   npm run preview"
echo ""

echo "✨ Available Commands:"
echo ""
echo "npm run dev              - Start development server"
echo "npm run build            - Build for production"
echo "npm run preview          - Preview production build"
echo "npm run json-server      - Start JSON Server"
echo ""

echo "📖 Documentation Files:"
echo ""
echo "• README.md              - Full feature documentation"
echo "• QUICKSTART.md          - Quick start guide"
echo "• ARCHITECTURE.md        - System architecture"
echo "• DELIVERY_SUMMARY.md    - Project summary"
echo "• FILES_INVENTORY.md     - Complete file listing"
echo ""

echo "🎯 Quick Start (3 Steps):"
echo ""
echo "Step 1: Terminal 1"
echo "  $ npm run json-server"
echo ""
echo "Step 2: Terminal 2"
echo "  $ npm run dev"
echo ""
echo "Step 3: Open Browser"
echo "  http://localhost:3000"
echo ""

echo "✅ System Status Check:"
echo ""
echo "After running setup, verify:"
echo "  - React app opens at http://localhost:3000"
echo "  - JSON Server responds at http://localhost:3001/stocks"
echo "  - No errors in browser console"
echo "  - Dashboard loads with sample data"
echo ""

echo "🔄 Restart the System:"
echo ""
echo "To stop: Press Ctrl+C in each terminal"
echo "To restart: Run the commands again"
echo ""

echo "❓ Troubleshooting:"
echo ""
echo "Port 3000/3001 already in use?"
echo "  - Kill the process using the port, or"
echo "  - Change port in vite.config.js (line 9)"
echo ""

echo "Cannot fetch stocks?"
echo "  - Ensure JSON Server is running on port 3001"
echo "  - Check browser console for network errors"
echo "  - Verify db.json exists in project root"
echo ""

echo "Form validation not working?"
echo "  - Check browser console for errors"
echo "  - Verify all required fields are filled"
echo "  - SKU must be unique and match format (ABC-123-001)"
echo ""

echo "✨ Ready to use! Start with the Quick Start steps above. 🚀"
